# Generated by Django 2.2.1 on 2020-05-11 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200510_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='task_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.Task'),
        ),
    ]
