# Generated by Django 2.2.1 on 2020-05-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200511_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='code',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
