# Generated by Django 2.2.1 on 2020-05-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_job_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='code',
            field=models.TextField(null=True),
        ),
    ]
