# Generated by Django 2.2.1 on 2020-05-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20200511_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
