# Generated by Django 2.2.1 on 2020-05-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20200511_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='assessment',
            field=models.IntegerField(null=True),
        ),
    ]
